### ISSUE TITLE
Swipe to Answer

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Dialer#127]
I think u want to change call screen UI. Because Now (call screen ui) is accidental touch to answer or reject the call. Pls change swipe to answer call UI so, we can reduce accidental touch to answer or reject the call. so, pls consider this issue to create UI change in SIMPLE DIALER 6.0👍

![IMG_20201210_100653_229](https://user-images.githubusercontent.com/75672019/101722622-9efe3300-3ad0-11eb-83c9-d4154932dfdb.jpg)

**Comment by Twiub** [comment]
Very important

**Comment by Pranab009** [comment]
Please add this feature..
This is very Handy feature.

**Comment by cyberpunkrocker-zero** [comment]
I strongly disagree with this topic. I changed from official Google dialer to Simple Dialer solely just **BECAUSE** I wanted to get rid of the Google dialer's stupid swipe-to-answer "feature". Please DO NOT remove the current green/red phone buttons! If you add a swipe-to-answer function, make it user-configurable whether the user want to use it or not.

**Comment by Midi-In** [comment]
I support this as well, could be user-configurable for those who really want to keep the current behaviour though.

**Comment by seniorm0ment** [comment]
I would assume this could be implemented as an option, but I agree I'd like to see it too. It helps deal with misclicks.
