### ISSUE TITLE
Option to disable "default phone app" checking

### ISSUE THREAD

**Issue by zwuss** [SimpleMobileTools/Simple-Dialer#211]
Hello, my simple dialer is not my default phone app (I use "yet another call blocker" as default for block calls without ring) and every time when I close&open simple dialer it ask "Make Dialer your default Phone app". Can you please add option to disable default phone app checking?
Android 8.1.0

**Comment by tibbi** [comment]
The app needs it to be able to handle calls and show Recents, the app doesnt really have any use if it isnt the default one.

**Comment by marcdw1289** [comment]
Y'know, I read this issue awhile back but the response has been sticking in my craw. Couldn't tell if it was due to lack of knowledge or just plain dismissive.

I have Yet Another Call Blocker set as the default Phone or Caller ID in a few ROMs. Custom Nougat and Android 11 OxygenOS.
Having YACB as the default allows it to catch and block scam and/or blacklisted numbers before the phone gets a chance to ring. Works great.
All other calls go straight through and the phone/dialer apps behave as they always have. Incoming/outgoing call behavior is not changed. Recent calls still show up in the phone app like normal.

Saying the phone app doesn't have any use if not set as the default is untrue.
