### ISSUE TITLE
Allow accepting/rejecting incoming calls without unlocking the screen first

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Dialer#574]
Some people report that if there is an incoming call, they have to unlock the screen first with the pin/pattern/biometrics

**Comment by wojted** [comment]
I have the same bug.  MIUI 14 Global (14.0.4.0 TKHMIXM).  PHONE MODEL Poco F3.  No root, bootloader locked.

**Comment by istvan-andrasi** [comment]
Also have to unlock before answering incoming calls.
Samsung S22 Galaxy

**Comment by yoda65** [comment]
Hi,
I don’t know if it could help you.
My phone is a Xiaomi mi note 10 pro running Miui 12, Android 10 lock with my fingerprint.
A the beginning (it  was 5.16 release, installed from playstore), when I received a call, the phone rang, but no window to take the call was displayed. 
I looked at app Android authorizes and set manualy some parameters. Since it works even with the latest updates 5.17.3 /.4  /5).
A second Xiaomi Redmi 10 phone had the same problem. I applied same setup with sucess.
This may be an installation bug (perhaps a conflict with miui security).

**_Simple dialer Android Autorisation :_**

Allow auto start=off

App permissions:
Contacts
Call logs
Microphone
Phone

Other Permissions:
Show on Lock screen=On
Display pop-up windows while running in the background=On 
Display pop-up window =on
Permanent notification=on

Notifications :
Show notifications=On
Show app icon badges=On
lock screen notifications=On
Allow sound=On
Allow vibration=On
Call_notification_channel (*)= Show notification

Battery saver: No restriction
Advanced setup:
Full screen mode=on


**_App setup :_**

STARTUP
Open the dialpad by default when the app open  **[   ]**

CALLS
Replace swiping at responding to incoming call with clicking **[X]**
Always display incoming calls on full screen **[X]**

Regards

**Comment by puresse** [comment]
Forgot to say, i'm also using fingerprint lock

**Comment by tibbi** [comment]
if you guys disable fingerprint or any device locking, does it work?

**Comment by tibbi** [comment]
and second question, are you using all the default settings in Simple Dialer, or you changed something?
