### ISSUE TITLE
Simple Dialer no longer pulls data from contacts on incoming call

### ISSUE THREAD

**Issue by ddundovic** [SimpleMobileTools/Simple-Dialer#577]
Since a couple of days ago (last update?) Simple Dialer no longer presents data (name, picture, ...) for an incoming call for a number that is stored in contacts. Afterwards name is shown in Call history.

Steps that I've tried:
- restart phone several times
- clear cache for the app
- clear data for the app
- check that all permissions are still checked
- switched to dialer app that came with the phone - it works
- tried to downgrade to last two prior versions of Simple Dialer - downgrade failed "due to unknown error"

Simple Dialer v5.17.5 is instaled from F-Droid repo on a Realme X2 phone, Android version is 11.

**Comment by tibbi** [comment]
try updating to 5.18.1 whenever it becomes available

**Comment by SIRSteiner** [comment]
Same here

Xiaomi Mi 9T Pro, MIUI Global 12.5.1.0 (Android 11)

**Comment by sphh** [comment]
@tibbi: Can you tell us, when version 5.18.1 will become available, so that we can decide, if it is worth to downgrade to 5.17.3? Thanks.

**Comment by tibbi** [comment]
I dont know, sometimes it takes Google quite a few days to review new app updates...

**Comment by ddundovic** [comment]
v5.17.8 pulls data from address book again! :)

**Comment by sphh** [comment]
@ddundovic: Lucky you! I upgraded to 5.17.8 and nothing has changed. I still get the ‘No contacts found’ error message and the history only displays the phone number and no names. I sync the contacts with DAVx⁵ and have more than one address book.

@tibbi: You explained, that the future version 5.18.1 will solve this problem. Has this fix brought forward?

**Comment by SIRSteiner** [comment]
Nearly the same here, v5.17.8 didn't solved the problem completely. Contacts (and phone books) are only visible if this app is set as the default dialer.
I also use DAVx⁵. Thank you

**Comment by sphh** [comment]
For me it is (and was always) the default dialer, still the contacts and the names in history are not displayed …

**Comment by tibbi** [comment]
I cannot reproduce it, any more info would help. Does the given contact have multiple numbers stored? What does the incoming call number and the stored number differ by? Just some prefix?

**Comment by sphh** [comment]
I might have lead you into wrong direction: For me no contact is visible at all (not even in the contacts or history list). Hence no information can be shown on incoming calls. Sorry for the confusion!

**Comment by tibbi** [comment]
are the misbehaving contacts stored at "Phone storage (not visible by other apps)" in Simple Contacts Pro or some other source, like Phone, SIM or so?

**Comment by SIRSteiner** [comment]
I did also again some tests. All my contacts are carddav contacts via DAVx⁵ and Nextcloud. I added one contact for the test at my phone storage.
1. Contacts (all) are only visible if this app is the default dialer. If not, contact list is empty but call history is visible.
2. The message of incoming AND outgoing calls from carddav contacts only shows the phone number. Call history shows number and name.
3. The message of incoming and outgoing calls from phone storage contacts shows number and name. Call history also.

I hope this helps...

**Comment by bdvore** [comment]
Hello
I was facing the same issue and all my contacts are managed with DAVx⁵. I tried to come back to the oldest version available in f-droid (5.17.6). But uninstalling and re-installing didn't change anything. No contact found.

Finally I came back to the default system phone app but Simple Dialer was still installed waiting for an update. After a few days, because the system app is too old not user friendly, I decided to restore Simple Dialer as the default system phone app. And going through this system configuration (in the system default app section) helped to restore the access to the contacts. It was quite unexpected and it was maybe a coincidence, but since my contacts are back. And I haven't tried to revert and reproduce.

I'm not sure it matters, but I have an old Sony Xperia X Compact with Android 8. 

I hope this helps...

**Comment by Occupant9589Carpet** [comment]
Mine is doing the same thing. My contacts are stored in the Simple Contacts Pro app but do not show in the Simple Dialer app. Permissions granted are Call Logs, Contacts, and Phone. Appear on top is allowed and Simple Dialer is the default app. It used to always work, but several updates ago it stopped. When the phone rings it only shows a number and not a name and contacts are not available on the contact tab on the Dialer app even though all of the contacts are in the Contacts Pro app. I either have to pick up the call that is only showing the numbers and maybe it is someone I know o r it maybe it is a dang sales call. Or I can just let it go to voicemail and when the call stops the contact will finally show on the missed call notification. Call history also shows all of the contact names. Contact names always show in every situation except for contacts tab and while the phone is ringing. I got tired of the bug and tried an experiment today and started downgrading versions until it started working again.  5.17.8, 5.17.7, 5.17.6, 5.17.5, and 5.17.4 all have the contacts problem. 5.17.3 was the first newest one that the contacts worked. I tried this test twice and the results were the same both times. Hopefully this information helps you narrow down the bug quicker and saves you time. I look forward to a new update that has the fix as I prefer to be on the latest version for security reasons. Thanks, have a good day, and let me know if you need anymore information.

**Comment by Merkost** [comment]
@Occupant9589Carpet, contacts without any phone number are not showing in dealer contacts tab. However they are showing in contacts. Could you please check if that's the case? Thanks

**Comment by Merkost** [comment]
If the issue still exists, is it possible for someone to create a CardDav with some fake contacts and share the link? Seems like the issue only is with DavX contacts. It's impossible to test or find the issue without independent testing.

**Comment by Occupant9589Carpet** [comment]
All of my contacts have phone numbers. I do not have any contacts that don't have a phone number. All of my contacts show in the Simple Contacts Pro app, but zero contacts show under the contacts tab in Simple Dialer app.

I am not sure if my contacts are DavX or not, I can export my contacts to a .vcf, delete my contacts, create some fake ones, export the fake ones to .vcf, then delete the fake ones, then import the original real contact .vcf. The only thing is I am not sure how to share the fake contacts .vcf. 

If there is a way, or someother way, I am willing to help. I technically minded, just not as technically minded as I wish I was. We all may feel that way though. Lol.

**Comment by Merkost** [comment]
@Occupant9589Carpet Could you please tell where are your contacts saved? Is it phone storage or google account for example? If it is the phone storage, is it the protected one (contacts which are hidden from other apps)?

**Comment by Occupant9589Carpet** [comment]
My contacts are saved in local phone storage only. They are all saved under vnd.sec.contact.phone. If I revert back to 5.17.3 it starts seeing the contacts again. All versions after 5.17.3 do not show the contacts. All versions before 5.17.3 work fine. I currently am running 5.17.3 on my phone as my daily driver so the contacts work. I hope to get this resolved so I can upgrade to the current version. The only thing that changes is the Dialer app version number, I change nothing with my contacts or contact app or contacts storage. So I don't think it is something on my end. I could be wrong because I am human. But if it is something about how my contacts are on my phone, it would have to be that the new versions of the Dialer app doesn't read them the way the Dialer app used to. Just guessing. I hope this information is helpful in troubleshooting. Let me know if I can do anything else to help.

**Comment by Merkost** [comment]
Thanks a lot for the additional information! In order to fix that issue, I will need you to export your contacts and send the vcf file here. You can import and export contacts in a simple contacts app menu. What I need is at least one contact that can be seen in 5.17.3 and can't in later versions.
![photo_2023-06-30 14 21 04](https://github.com/SimpleMobileTools/Simple-Dialer/assets/56008710/e178fc59-da51-4c10-a480-bba3a2337c7d)

**Comment by Occupant9589Carpet** [comment]
![Screenshot_Dialer_1](https://github.com/SimpleMobileTools/Simple-Dialer/assets/113854595/7491dd89-14a2-49d0-a582-37944272f514)

[bcontacts_2023_07_09_07_54_51.zip](https://github.com/SimpleMobileTools/Simple-Dialer/files/11997337/bcontacts_2023_07_09_07_54_51.zip)

Sorry it took me a little while to respond things have been hectic. I don't know if I have mentioned it before, but one detail is when using a Dialer App version later than 5.17.3 under contacts the "Request Access" doesn't request access. Instead it tries to create a new contact. Attached you will find a picture of what I am talking about as well as a .vcf in a .zip file that has 2 fake contacts that can be seen in 5.17.3 and earlier versions and not in versions later than 5.17.3. I hope this helps and let me know if you need anything else from me. Thanks.

**Comment by Occupant9589Carpet** [comment]
Any luck figuring out the issue? Let me know if you need anything on my end. Thank you.

**Comment by sphh** [comment]
@tibbi, you mentioned in https://github.com/SimpleMobileTools/Simple-Dialer/issues/577#issuecomment-1501150769:
> try updating to 5.18.1 whenever it becomes available

v5.18.1 has now become available. @tibbi can you please confirm, that this problem has been resolved, before I install the new version and then have to downgrade again. Many thanks.

**Comment by SIRSteiner** [comment]
I gave v5.18.1 (F-Droid) another try today and it seem to work correctly. Let me use Simple Dialer 3-4 days and I will confirm it again or not.

Many thanks for your work!

**Comment by SIRSteiner** [comment]
Update 1:
Contacts of incoming calls in history are not visible until I open the DW Phone app. I don't know why?

If you need this info: Simple Dialer is the default phone ap.

**Comment by Occupant9589Carpet** [comment]
5.18.1 seems to be working. I will report back if there are any problems.
